// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer2 from "./components/layout/Footer2";
import { ToastContainer } from "react-toastify";
import CombinedHeader from "./components/layout/combinedHeader";


export const metadata = {
  title: "Recruitment Portal | MECON Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <CombinedHeader/>
          <ToastContainer />
          <div className=" min-h-screen w-full flex items-center justify-center">
            <main className="w-full bg-blue-50 ">{children}</main>
          </div>
          {/* <Footer /> */}
          <Footer2 />
        </div>
      </body>
    </html>
  );
}
