// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Navbar from "./components/layout/Navbar";
import Footer2 from "./components/layout/Footer2";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Recruitment Portal | MECON Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <Navbar />
          <Header />
          <div className=" min-h-screen w-full flex items-center justify-center">
            <main className="w-full bg-blue-50 ">{children}</main>
          </div>
          {/* <Footer /> */}
          <Footer2 />
        </div>
      </body>
    </html>
  );
}
